const config = {
    'API_BASE': 'https://api-osm-comments-staging.tilestream.net/api/v1/',
    'MAPBOX_ACCESS_TOKEN': 'pk.eyJ1Ijoic2FuamF5YiIsImEiOiI3NjVvMFY0In0.byn_eCZGAwR1yaPeC-SVKw',
    'OSM_BASE': 'https://www.openstreetmap.org/',
    'STATIC_MAPS_BASE': 'https://api.mapbox.com/v4/mapbox.streets/',
    'USERS': [
        'PlaneMad',
        'andygol',
        'mikelmaron',
        'Rub21',
        'ediyes',
        'Luis36995',
        'dannykath',
        'RichRico',
        'ruthmaben',
        'abel801',
        'samely',
        'calfarome',
        'srividya_c',
        'Chetan_Gowda',
        'ramyaragupathy',
        'lxbarth',
        'nikhilprabhakar',
        'jinalfoflia',
        'pratikyadav',
        'aarthy',
        'oini',
        'Jothirnadh',
        'saikabhi',
        'geohacker',
        'shvrm',
        'karitotp',
        'manings',
        'sanjayb',
        'Arunasank',
        'bkowshik',
        'nammala',
        'poornibadrinath'
    ]
};

export default config;
